# Generated by Django 3.1 on 2020-08-19 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
