# Generated by Django 3.1 on 2020-08-19 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_App', '0002_auto_20200819_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
