# Generated by Django 3.1 on 2020-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_App', '0004_auto_20200819_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='is_boast',
            field=models.BooleanField(default=False),
        ),
    ]
