# Generated by Django 3.1 on 2020-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_App', '0006_auto_20200819_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastorroast',
            old_name='score',
            new_name='down_votes',
        ),
        migrations.AddField(
            model_name='boastorroast',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
