# Generated by Django 3.1 on 2020-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_App', '0007_auto_20200820_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastorroast',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
